# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Executable
      run: ./gradlew createDistributable
    - name: Build JAR
      run: ./gradlew packageReleaseUberJarForCurrentOS
    - shell: bash
      run: |
        ls -R
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-Linux
        path: ./build/compose/binaries/main/app
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-Linux-JAR
        path: ./build/compose/jars

  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Executable
      run: ./gradlew createDistributable
    - name: Build JAR
      run: ./gradlew packageReleaseUberJarForCurrentOS
    - shell: bash
      run: |
        ls -R
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-Windows
        path: ./build/compose/binaries/main/app
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-Windows-JAR
        path: ./build/compose/jars

  macOS:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Executable
      run: ./gradlew createDistributable
    - name: Build JAR
      run: ./gradlew packageReleaseUberJarForCurrentOS
    - shell: bash
      run: |
        ls -R
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-MacOS
        path: ./build/compose/binaries/main/app
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: TrackerV2-MacOS-JAR
        path: ./build/compose/jars
